create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  emoji text not null default '🍮',
  badge text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

grant select on table public.products to anon, authenticated;

insert into public.products (name, description, price, emoji, badge)
select * from (values
  ('Pudín de vainilla', 'Suave, cremoso y con vainilla de verdad.', 4.50, '🍮', 'Favorito'),
  ('Pudín de chocolate', 'Chocolate intenso con textura sedosa.', 5.00, '🍫', 'Clásico'),
  ('Pudín de fresa', 'Dulce, fresco y con trocitos de fresa.', 5.25, '🍓', 'Nuevo'),
  ('Pudín de caramelo', 'Cremoso con una capa brillante de caramelo.', 5.50, '✨', 'Especial'),
  ('Pudín de coco', 'Tropical, ligero y coronado con coco rallado.', 5.25, '🥥', null),
  ('Pudín arcoíris', 'Una edición divertida con sabores sorpresa.', 6.00, '🌈', 'Edición limitada')
) as seed(name, description, price, emoji, badge)
where not exists (select 1 from public.products);
